using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates CE Lua invoke scripts for UFunction calls.
/// Uses the shared memory mailbox (g_invokeMailbox) for communication with UE5Dumper DLL.
/// No remote thread injection needed — uses ReadProcessMemory/WriteProcessMemory only.
///
/// IMPORTANT: All Lua string literals use single quotes ('...') to avoid
/// JSON double-quote escaping issues when transmitted via the AOBMaker pipe.
/// Line endings are normalized to LF-only (\n) for CE compatibility.
/// </summary>
public static class InvokeScriptGenerator
{
    // Mailbox offsets (must match Mailbox.h MailboxData struct)
    private const string OffCmd          = "0x000";
    private const string OffStatus       = "0x004";
    private const string OffResult       = "0x008";
    private const string OffInstanceAddr = "0x010";
    private const string OffUfuncAddr    = "0x018";
    private const string OffParmsSize    = "0x020";
    private const string OffNumParms     = "0x022";
    private const string OffFuncFlags    = "0x024";
    private const string OffClassName    = "0x028";
    private const string OffFuncName     = "0x128";
    private const string OffErrorMsg     = "0x228";
    private const string OffParamsData   = "0x328";

    /// <summary>
    /// Generate a complete CE AA script that invokes a UFunction via mailbox.
    /// </summary>
    public static string Generate(string className, string funcName, FunctionInfoModel func)
    {
        var sb = new StringBuilder(8192);
        var inputParams = func.Params.Where(p => !p.IsReturn).ToList();
        var hasParams = inputParams.Count > 0;

        Line(sb, "[ENABLE]");
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        Line(sb, "-- ================================================================");
        Line(sb, $"-- UFunction Invoker: {className}::{funcName}");
        Line(sb, "-- Generated by UE5CEDumper -- uses shared memory mailbox");
        Line(sb, "-- No remote thread injection needed (pure memory read/write)");
        Line(sb, "-- ================================================================");
        Line(sb);

        // Constants
        Line(sb, $"local OWNER_CLASS  = '{EscapeLua(className)}'");
        Line(sb, $"local FUNC_NAME    = '{EscapeLua(funcName)}'");
        Line(sb, $"local PARMS_SIZE   = {func.ParmsSize}");
        Line(sb);

        // Forward-declare mb so helper closures can capture the upvalue
        Line(sb, "local mb");
        Line(sb);

        // Mailbox helpers
        AppendMailboxHelpers(sb);

        // Find mailbox symbol
        AppendMailboxDetection(sb);

        // Instance resolver via CMD_FIND_INSTANCE
        AppendInstanceResolver(sb);

        // Function resolver via CMD_FIND_FUNCTION
        AppendFunctionResolver(sb);

        // Print resolved info
        Line(sb, "print(string.format('  Resolved: %s::%s', OWNER_CLASS, FUNC_NAME))");
        Line(sb, "print(string.format('  Instance: 0x%X  |  UFunction: 0x%X', instanceAddr, ufuncPtr))");
        Line(sb);

        if (hasParams)
        {
            AppendParamForm(sb, className, funcName, inputParams, func.ParmsSize);
        }
        else
        {
            AppendDirectInvoke(sb, func.ParmsSize);
        }

        Line(sb, "{$asm}");
        Line(sb, "[DISABLE]");
        Line(sb, "{$lua}");
        Line(sb, "-- nop");
        Line(sb, "{$asm}");

        return sb.ToString();
    }

    /// <summary>Append a line with LF-only ending (no CR).</summary>
    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }

    private static void AppendMailboxHelpers(StringBuilder sb)
    {
        Line(sb, "-- Mailbox helpers (read/write target process memory via CE)");
        Line(sb, "local function writeMbStr(offset, str)");
        Line(sb, "    local bytes = {}");
        Line(sb, "    for i = 1, math.min(#str, 255) do bytes[#bytes+1] = string.byte(str, i) end");
        Line(sb, "    bytes[#bytes+1] = 0");
        Line(sb, "    writeBytes(mb + offset, bytes)");
        Line(sb, "end");
        Line(sb, "local function waitDone(timeoutMs)");
        Line(sb, "    local elapsed = 0");
        Line(sb, $"    while readInteger(mb + {OffStatus}) ~= 1 do");
        Line(sb, "        sleep(1)");
        Line(sb, "        elapsed = elapsed + 1");
        Line(sb, "        if elapsed >= (timeoutMs or 10000) then");
        Line(sb, $"            local err = readString(mb + {OffErrorMsg}, 256) or 'timeout'");
        Line(sb, "            error('[Invoke] Mailbox timeout: ' .. err)");
        Line(sb, "        end");
        Line(sb, "    end");
        Line(sb, "end");
        Line(sb, "local function readErr()");
        Line(sb, $"    return readString(mb + {OffErrorMsg}, 256) or 'Unknown error'");
        Line(sb, "end");
        Line(sb);
    }

    private static void AppendMailboxDetection(StringBuilder sb)
    {
        Line(sb, "-- Find mailbox symbol (exported by UE5Dumper DLL)");
        Line(sb, "mb = getAddress('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, "    mb = getAddress('UE5Dumper.g_invokeMailbox')");
        Line(sb, "end");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, "    print('ERROR: g_invokeMailbox not found!')");
        Line(sb, "    showMessage('ERROR: g_invokeMailbox not found!\\nMake sure UE5Dumper DLL is loaded (version.dll Proxy or CE inject).')");
        AppendCleanupTimer(sb, 1);
        Line(sb, "    return");
        Line(sb, "end");
        Line(sb, "print(string.format('  [Invoke] Mailbox at 0x%X', mb))");
        Line(sb);
    }

    private static void AppendInstanceResolver(StringBuilder sb)
    {
        Line(sb, "-- Find a live instance via mailbox CMD_FIND_INSTANCE (2)");
        Line(sb, $"writeMbStr({OffClassName}, OWNER_CLASS)");
        Line(sb, $"writeInteger(mb + {OffStatus}, 0)");
        Line(sb, $"writeInteger(mb + {OffCmd}, 2)");
        Line(sb, "waitDone()");
        Line(sb);

        Line(sb, $"local instanceAddr = readQword(mb + {OffInstanceAddr})");
        Line(sb, $"if readInteger(mb + {OffResult}) ~= 0 or instanceAddr == 0 then");
        Line(sb, "    local err = readErr()");
        Line(sb, "    print('ERROR: No instance of [' .. OWNER_CLASS .. '] found: ' .. err)");
        Line(sb, "    showMessage('ERROR: No live instance of [' .. OWNER_CLASS .. '] found!\\n' .. err .. '\\nMake sure you are in-game.')");
        AppendCleanupTimer(sb, 1);
        Line(sb, "    return");
        Line(sb, "end");
        Line(sb);
    }

    private static void AppendFunctionResolver(StringBuilder sb)
    {
        Line(sb, "-- Find UFunction via mailbox CMD_FIND_FUNCTION (3)");
        Line(sb, $"writeQword(mb + {OffInstanceAddr}, instanceAddr)");
        Line(sb, $"writeMbStr({OffFuncName}, FUNC_NAME)");
        Line(sb, $"writeInteger(mb + {OffStatus}, 0)");
        Line(sb, $"writeInteger(mb + {OffCmd}, 3)");
        Line(sb, "waitDone()");
        Line(sb);

        Line(sb, $"local ufuncPtr = readQword(mb + {OffUfuncAddr})");
        Line(sb, $"if readInteger(mb + {OffResult}) ~= 0 or ufuncPtr == 0 then");
        Line(sb, "    print(string.format('ERROR: Function [%s] not found on %s!', FUNC_NAME, OWNER_CLASS))");
        Line(sb, "    showMessage(string.format('ERROR: Function [%s] not found on %s!', FUNC_NAME, OWNER_CLASS))");
        AppendCleanupTimer(sb, 1);
        Line(sb, "    return");
        Line(sb, "end");
        Line(sb);
    }

    private static void AppendDirectInvoke(StringBuilder sb, int parmsSize)
    {
        Line(sb, "-- No parameters -- invoke directly via CMD_INVOKE (1)");

        // Zero out params_data (even for void functions, clear the buffer)
        if (parmsSize > 0)
        {
            Line(sb, $"local PD = mb + {OffParamsData}");
            Line(sb, $"for i = 0, {parmsSize - 1} do writeByte(PD + i, 0) end");
        }

        Line(sb, $"writeQword(mb + {OffInstanceAddr}, instanceAddr)");
        Line(sb, $"writeQword(mb + {OffUfuncAddr}, ufuncPtr)");
        Line(sb, $"writeInteger(mb + {OffStatus}, 0)");
        Line(sb, $"writeInteger(mb + {OffCmd}, 1)");
        Line(sb, "print('  Invoking via mailbox...')");
        Line(sb, "waitDone()");
        Line(sb);

        Line(sb, $"local result = readInteger(mb + {OffResult})");
        Line(sb, "if result == 0 then print('  INVOKED OK!')");
        Line(sb, "else print('  INVOKE FAILED: error code ' .. tostring(result) .. ' ' .. readErr()); showMessage('INVOKE FAILED:\\nerror code ' .. tostring(result)) end");
        AppendCleanupTimer(sb, 0);
        Line(sb);
    }

    private static void AppendParamForm(StringBuilder sb, string className, string funcName,
        List<FunctionParamModel> inputParams, int parmsSize)
    {
        Line(sb, "-- ================================================================");
        Line(sb, "-- Build parameter input form");
        Line(sb, "-- ================================================================");
        Line(sb, $"local PARAM_COUNT = {inputParams.Count}");
        Line(sb, "local labelW = 280");
        Line(sb, "local editW = 160");
        Line(sb, "local rowH = 28");
        Line(sb, "local btnH = 50");
        Line(sb, "local yPos = 10");
        Line(sb, "local contentH = math.max(PARAM_COUNT, 1) * rowH + 20");
        Line(sb, "local formH = math.min(contentH + btnH + 50, 600)");
        Line(sb, "local formW = labelW + editW + 40");
        Line(sb);
        Line(sb, "local frm = createForm(false)");
        Line(sb, "frm.Caption = string.format('%s::%s  |  0x%X', OWNER_CLASS, FUNC_NAME, instanceAddr)");
        Line(sb, "frm.Width = formW");
        Line(sb, "frm.Height = formH");
        Line(sb, "frm.Position = poScreenCenter");
        Line(sb, "frm.BorderStyle = bsSizeable");
        Line(sb);
        Line(sb, "local edits = {}");

        // Generate labels + edit fields
        for (int i = 0; i < inputParams.Count; i++)
        {
            var p = inputParams[i];
            var label = $"{p.Name}  [{ShortTypeName(p.TypeName)}, {p.Size} B{(p.IsOut ? ", out" : "")}]";
            var defaultVal = GetDefaultValue(p.TypeName);
            int idx = i + 1;

            Line(sb, "    do");
            Line(sb, "        local lbl = createLabel(frm)");
            Line(sb, $"        lbl.Caption = '{EscapeLua(label)}'");
            Line(sb, "        lbl.Left = 10");
            Line(sb, "        lbl.Top = yPos + 2");
            Line(sb, "        lbl.AutoSize = true");
            Line(sb, "        local edt = createEdit(frm)");
            Line(sb, $"        edt.Text = '{defaultVal}'");
            Line(sb, "        edt.Left = labelW + 20");
            Line(sb, "        edt.Top = yPos");
            Line(sb, "        edt.Width = editW");
            Line(sb, $"        edits[{idx}] = edt");
            Line(sb, "        yPos = yPos + rowH");
            Line(sb, "    end");
        }

        // Buttons
        Line(sb);
        Line(sb, "local btnY = formH - btnH - 10");
        Line(sb, "local btnFire = createButton(frm)");
        Line(sb, "btnFire.Caption = 'FIRE'");
        Line(sb, "btnFire.Width = 120");
        Line(sb, "btnFire.Height = 34");
        Line(sb, "btnFire.Left = 10");
        Line(sb, "btnFire.Top = btnY");
        Line(sb);
        Line(sb, "local btnCancel = createButton(frm)");
        Line(sb, "btnCancel.Caption = 'Cancel'");
        Line(sb, "btnCancel.Width = 90");
        Line(sb, "btnCancel.Height = 34");
        Line(sb, "btnCancel.Left = 140");
        Line(sb, "btnCancel.Top = btnY");
        Line(sb, "btnCancel.OnClick = function() frm.close() end");
        Line(sb);

        // On close: deactivate memrec
        Line(sb, "frm.OnClose = function(sender)");
        AppendCleanupTimer(sb, 1);
        Line(sb, "    return caFree");
        Line(sb, "end");
        Line(sb);

        // Fire button logic — write params to mailbox, then CMD_INVOKE
        Line(sb, "btnFire.OnClick = function()");
        Line(sb, $"    local PD = mb + {OffParamsData}");

        // Zero-fill params buffer
        Line(sb, $"    for i = 0, {parmsSize - 1} do writeByte(PD + i, 0) end");

        // Write each param to the mailbox params_data at its offset
        for (int i = 0; i < inputParams.Count; i++)
        {
            var p = inputParams[i];
            int idx = i + 1;
            var parseExpr = GetParseExpression(p.TypeName, idx);
            var writeStmt = GetMailboxWriteStatement(p.TypeName, p.Size, p.Offset, parseExpr);
            Line(sb, $"    {writeStmt}");
        }

        Line(sb, $"    writeQword(mb + {OffInstanceAddr}, instanceAddr)");
        Line(sb, $"    writeQword(mb + {OffUfuncAddr}, ufuncPtr)");
        Line(sb, $"    writeInteger(mb + {OffStatus}, 0)");
        Line(sb, $"    writeInteger(mb + {OffCmd}, 1)");
        Line(sb, "    print('  Invoking via mailbox...')");
        Line(sb, "    waitDone()");
        Line(sb, $"    local result = readInteger(mb + {OffResult})");
        Line(sb, "    if result == 0 then print('  INVOKED OK!')");
        Line(sb, "    else print('  INVOKE FAILED: error code ' .. tostring(result) .. ' ' .. readErr()); showMessage('INVOKE FAILED:\\nerror code ' .. tostring(result)) end");

        Line(sb, "    frm.close()");
        Line(sb, "end");
        Line(sb);
        Line(sb, "frm.show()");
        Line(sb);
    }

    private static void AppendCleanupTimer(StringBuilder sb, int indent)
    {
        var pad = new string(' ', indent * 4);
        Line(sb, $"{pad}local t = createTimer(nil, false)");
        Line(sb, $"{pad}t.Interval = 100");
        Line(sb, $"{pad}t.OnTimer = function(s) s.Enabled = false; s.destroy(); if memrec then memrec.Active = false end end");
        Line(sb, $"{pad}t.Enabled = true");
    }

    /// <summary>Generate a CE Lua write statement for a param in the mailbox params_data buffer.</summary>
    private static string GetMailboxWriteStatement(string typeName, int size, int offset, string valueExpr)
    {
        string writeFunc = typeName switch
        {
            "BoolProperty" or "ByteProperty" or "Int8Property"
                => "writeBytes",
            "Int16Property" or "UInt16Property"
                => "writeSmallInteger",
            "FloatProperty"
                => "writeFloat",
            "DoubleProperty"
                => "writeDouble",
            "Int64Property" or "UInt64Property"
                or "NameProperty" or "ObjectProperty" or "ClassProperty"
                or "SoftObjectProperty" or "WeakObjectProperty"
                or "LazyObjectProperty" or "InterfaceProperty"
                => "writeQword",
            "IntProperty" or "UInt32Property" or "EnumProperty"
                => "writeInteger",
            _ => size switch
            {
                1 => "writeBytes",
                2 => "writeSmallInteger",
                8 => "writeQword",
                _ => "writeInteger",
            },
        };

        // writeBytes takes a table: writeBytes(addr, {val})
        if (writeFunc == "writeBytes")
            return $"writeBytes(PD + {offset}, {{{valueExpr}}})";

        return $"{writeFunc}(PD + {offset}, {valueExpr})";
    }

    /// <summary>Short display name for param type label.</summary>
    private static string ShortTypeName(string typeName)
    {
        return typeName switch
        {
            "BoolProperty" => "bool",
            "ByteProperty" => "uint8",
            "Int8Property" => "int8",
            "Int16Property" => "int16",
            "UInt16Property" => "uint16",
            "IntProperty" => "int32",
            "UInt32Property" => "uint32",
            "Int64Property" => "int64",
            "UInt64Property" => "uint64",
            "FloatProperty" => "float",
            "DoubleProperty" => "double",
            "NameProperty" => "FName",
            "ObjectProperty" => "UObject*",
            "ClassProperty" => "UClass*",
            "StrProperty" => "FString",
            "TextProperty" => "FText",
            "EnumProperty" => "enum",
            "StructProperty" => "struct",
            _ => typeName.Replace("Property", ""),
        };
    }

    /// <summary>Default edit field value for a type.</summary>
    private static string GetDefaultValue(string typeName)
    {
        return typeName switch
        {
            "FloatProperty" or "DoubleProperty" => "0.0",
            "BoolProperty" => "0",
            "NameProperty" or "ObjectProperty" or "ClassProperty"
                or "SoftObjectProperty" or "WeakObjectProperty"
                or "InterfaceProperty" => "0x0",
            _ => "0",
        };
    }

    /// <summary>Lua expression to parse edit field text into a numeric value.</summary>
    private static string GetParseExpression(string typeName, int editIndex)
    {
        // Pointer/FName types: hex-aware parsing
        if (typeName is "NameProperty" or "ObjectProperty" or "ClassProperty"
            or "SoftObjectProperty" or "WeakObjectProperty" or "InterfaceProperty")
        {
            return $"(function() local s = edits[{editIndex}].Text; " +
                   "if s:sub(1,2) == '0x' or s:sub(1,2) == '0X' then " +
                   "return tonumber(s, 16) or 0 else return tonumber(s) or 0 end end)()";
        }

        // Float types: direct tonumber
        if (typeName is "FloatProperty" or "DoubleProperty")
            return $"tonumber(edits[{editIndex}].Text) or 0.0";

        // Integer types: floor to avoid fractional
        return $"math.floor(tonumber(edits[{editIndex}].Text) or 0)";
    }

    /// <summary>Escape special characters for Lua single-quoted string literal.</summary>
    private static string EscapeLua(string s)
    {
        return s.Replace("\\", "\\\\").Replace("'", "\\'").Replace("\n", "\\n");
    }
}
